### ISSUE TITLE
Fetch commands from data

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/OC-discord-bot#13]
Complete the command `tag` to fetch the response from `data.json`
- Follow proper indentation.
- [Hint] Checkout the initial "-hi" command.

## Submission guidelines -
- Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
- Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by GammaMicrowave** [comment]
claim

**Comment by MistyRavager** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @GammaMicrowave

**Comment by Atharv23m** [comment]
Completed
