### ISSUE TITLE
Add error message

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/OC-discord-bot#16]
If a particular command doesn't exist in `data.json` return an error message. (This command is an edit to the already existing `-tag` command)

### Submission guidelines -
- Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
- Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by frikinomad** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @frikinomad

**Comment by frikinomad** [comment]
waiting for new token
