### ISSUE TITLE
Add create command

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/OC-discord-bot#17]
Create a command to add new responses in `data.json`

The command should follow the following outline: `-create [tag name] [response]`

### Submission guidelines -
- Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
- Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Im-Madhur-Gupta** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @GammaMicrowave
