### ISSUE TITLE
Add a weather command

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/OC-discord-bot#29]
Complete the command `-weather` to fetch the weather at a location
- The syntax for the command should be `-weather [location]`
- You need to fetch all the relevant information like temperature, humidity and rain etc
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation.

#### Submission guidelines -
- Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
- Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by GammaMicrowave** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @GammaMicrowave
