### ISSUE TITLE
Add birthday command

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#33]
Complete the command `-birthdays` to fetch the birthdays from the following API https://gpl-at-iiita.anurag10jain.repl.co
- The syntax for the command should be `-birthdays `
- You need to fetch all the relevant information like name, course, roll no. etc.
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation.

#### Submission guidelines -
- Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
- Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by frikinomad** [comment]
Claim

**Comment by Atharv23m** [comment]
Assigned to @frikinomad
