### ISSUE TITLE
Add command to view Avatar of a Discord User

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#34]
Create the command to fetch the avatar of any  Discord user in the server.

- The syntax for the command should be -av [user].
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation.
#### Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @GammaMicrowave
