### ISSUE TITLE
Different tags for different servers

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#36]
Currently the tag commands are common for all servers.

- The tag commands created in a Server A should not be accesible in Server B.
- Edit the command so the tags remain server specific.
- [HINT] Create different .json file in the data folder for different servers and access them accordingly using server ID.

Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by frikinomad** [comment]
claim

**Comment by Atharv23m** [comment]
@frikinomad you already have one issue assigned.

**Comment by frikinomad** [comment]
Already have a pr for it

**Comment by frikinomad** [comment]
Waiting for someone to merge it

**Comment by pvtr03** [comment]
Assigned to @frikinomad

**Comment by pvtr03** [comment]
@frikinomad whats your progress on this issue?

**Comment by pvtr03** [comment]
The issue is open for claims again!

**Comment by GammaMicrowave** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @GammaMicrowave
