### ISSUE TITLE
Command to know Points of a specific user in OpenCode

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#40]
Create a command that fetches the points of a OpenCode participant using  the following API -
https://leaderboard-response-cache.anurag10jain.repl.co/get-all-data

- The command syntax should be  -points [GitHub Username]
- It should return the total current points of the user and the list of repo's contributed by the user.
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation. 

Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.](https://leaderboard-response-cache.anurag10jain.repl.co/get-all-data)

**Comment by MistyRavager** [comment]
Claim

**Comment by Atharv23m** [comment]
Assigned to @MistyRavager
