### ISSUE TITLE
Command to fetch Leaderboard for OpenCode

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#41]
Create a command that fetches leaderboard of OpenCode using the following API -
https://leaderboard-response-cache.anurag10jain.repl.co/get-all-data

- The command syntax should be  -lb
- It should return the top 10 contributers from the leaderboard data.
- The top 3 should be highlighted accordingly in the embed.
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation. 

Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.](https://leaderboard-response-cache.anurag10jain.repl.co/get-all-data)

**Comment by GammaMicrowave** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @GammaMicrowave
