### ISSUE TITLE
Fetch meme 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#44]
Create the command to fetch a random meme from reddit.

- The syntax for the command should be -meme.
- Can also specify subreddit, syntax will be -meme [subreddit].
- If no subredddit specified, grab memes from the default popular subs.
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation.
#### Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by MistyRavager** [comment]
Claim

**Comment by Atharv23m** [comment]
Assigned to @MistyRavager
