### ISSUE TITLE
Fetch Random Pokemon 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#45]
Create the command to fetch a random Pokemon and send its sprite and PokeDex entry using PokeAPI
https://pokeapi.co/docs/v2#info

- The syntax for the command should be -pokemon.
- Fetch a random Pokemon from the total of first 500 pokemons, (refer to doc for ids).
- Fetch its name, sprite, Generation and Pokedex entry.
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation.
#### Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by MistyRavager** [comment]
claim

**Comment by akshatsgh** [comment]
Claim

**Comment by Atharv23m** [comment]
Issue assigned to @MistyRavager

**Comment by sanyam1259** [comment]
claim
