### ISSUE TITLE
Movie rating command

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#59]
Create the command to fetch a movie info from IMDB using following API
https://developers.themoviedb.org/3/getting-started/introduction

- The syntax for the command should be -movie [movie name].
- Fetch the ratings, cast, synopsis etc for the given movie.
- Make sure to use [discord embeds](https://plainenglish.io/blog/send-an-embed-with-a-discord-bot-in-python)
- Follow proper indentation.
#### Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by 88oo** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @Koshal7
