### ISSUE TITLE
Design Home Page for OC-discord bot

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#6]
This issue is for all the design enthusiasts, Design a homepage for the OC-discord bot in Figma 
It should include the following elements
- Invite link 
- Description 
- Background and UI 
- Invitation to Opencode server
- Invitation to the Repo webpage
-  Anything more you can add 
### Submission guidelines - 
- Add your Figma link in the 'designs.json' file.
- Make sure the visibility of the Figma File is public.
- Note that the issue is Open for All. There is no need to claim this issue. You can directly submit a PR

**Comment by lilTud21** [comment]
Please assign me this issue
